import type { AppProps } from "next/app";
import Head from "next/head";
import { Provider } from "react-redux";
import { QueryClient, QueryClientProvider } from "react-query";
import { store } from "@/store/store";
import GlobalStyle from "@/styles/Global.style";
import GlobalLayout from "@/components/Layouts/GlobalLayout";

export default function App({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();
  return (
    <>
      <Head>
        <title>Qumunity-next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Provider store={store}>
          <GlobalStyle />
          <GlobalLayout>
            <Component {...pageProps} />
          </GlobalLayout>
        </Provider>
      </QueryClientProvider>
    </>
  );
}
