import type { AppProps } from "next/app";
import { NextPage } from "next";
import Head from "next/head";
import { Provider } from "react-redux";
import { QueryClient, QueryClientProvider } from "react-query";
import { store } from "@/store/store";
import GlobalStyle from "@/styles/Global.style";
import { AuthGaurdLayout, GlobalLayout } from "@/components/Layouts";

type NextPageWithAuthLayout<P = {}, IP = P> = NextPage<P, IP> & {
  auth?: boolean;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithAuthLayout;
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const queryClient = new QueryClient();
  return (
    <>
      <Head>
        <title>Qumunity-next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Provider store={store}>
          <GlobalStyle />
          <GlobalLayout>
            {Component.auth ? (
              <AuthGaurdLayout>
                <Component {...pageProps} />
              </AuthGaurdLayout>
            ) : (
              <Component {...pageProps} />
            )}
          </GlobalLayout>
        </Provider>
      </QueryClientProvider>
    </>
  );
}
